### ISSUE TITLE
Allow re-negotiation for DTLS 1.2

### ISSUE THREAD

**Issue by tuexen** [gloinul/draft-westerlund-tsvwg-dtls-over-sctp-bis#12]
To allow refreshing the keys.

**Comment by emanjon** [comment]
Renegotiation seems to be disabled by default  in many DTLS implementation due to security problems. Might be ok to use as long as RFC 5476 is mandates, but my understanding is some security isssues still remain. Also not perfect to rely on parts of TLS libraries that are normally disables.

https://security.stackexchange.com/questions/24554/should-i-use-ssl-tls-renegotiation/230327#230327

I made a PR that allows renegotiation and added security considerations.

**Comment by gloinul** [comment]
So, the PR was #21 and that was merged after direct discussion and review.

**Comment by gloinul** [comment]
Issue ready to be closed in my view.
