### ISSUE TITLE
Processing fragments and flow control

### ISSUE THREAD

**Issue by martinthomson** [gloinul/draft-westerlund-tsvwg-dtls-over-sctp-bis#131]
https://gloinul.github.io/draft-westerlund-tsvwg-dtls-over-sctp-bis/draft-ietf-tsvwg-dtls-over-sctp-bis.html#section-3.3-4 says:

> However, for efficient operation and avoiding flow control stalls if user message fragments are not frequently and expiendtly moved to upper layer memory buffers, the receiver buffer needs to be larger.

(Note the typo here: expediently; though there might be a better word to use for this.)

I don't think that this is good advice.  Or maybe this is unclear and it could be improved.  It would be ideal if the SCTP stack, with its flow control, is used to maintain back-pressure on the sending side.  Pulling data out of buffers in the stack and putting them somewhere (¯\\\_(ツ)\_/¯) hides the buffering from the flow control mechanism.  I'm pretty sure that you aren't suggesting that, but this might be read as doing that.

**Comment by gloinul** [comment]
So in relation to the text I wrote in #135 I would note that there is a need to move data from the receiver window into the DTLS record reassembly so that they can be timely dispatched. 

The aspect of back-pressure is possible to do. So that if the ULP don't read buffered decrypted data the DTLS/SCTP layer don't read up new data into the re-assembly buffer to keep the data buffered in the receiver DTLS/SCTP layer limited.

I think this is part of a re-write around buffering and its implementation to take care of the other aspects that #135 discusses.
