### ISSUE TITLE
User messages are inefficient

### ISSUE THREAD

**Issue by martinthomson** [gloinul/draft-westerlund-tsvwg-dtls-over-sctp-bis#141]
Several things here...

Given that the content of user messages is protected in pieces, SCTP-AUTH only provides protection for:

* The mapping of DTLS records to the correct user message
* The order of DTLS records with a user message
* The DTLS record that starts and ends a user message

If the content of user messages is limited to application_data, then the only value the enclosed content type adds is the ability to pad each record.

The DTLS record header contains redundant information.  Some of this only needs to appear once for each user message:

* The epoch (apparently key updates cannot occur during a message, I don't know why)
* The connection ID (unless these can change mid-message; I haven't seen requirements regarding that yet)
* The header format (this is effectively fixed)

DTLS 1.2 records have a useless version and content-type field on top of that.

**Comment by gloinul** [comment]
Yes, it is inefficient and the reason is that we want to be able to implement this on top of existing SCTP stacks, not having to refactor the SCTP stacks completely. If one would go down a complete refactoring of the protocol one would integrate the packet protection based on the TSN level resulting a single linear packet stream simplifying a lot of the other complexities around key-update etc. 

However, if one is doing such a significant change I think I would argue for considering deploying MP-QUIC as transport protocol instead of SCTP.

My proposal is to simply accept this and move on.
