### ISSUE TITLE
Allow DTLS 1.3 KeyUpdate

### ISSUE THREAD

**Issue by martinthomson** [gloinul/draft-westerlund-tsvwg-dtls-over-sctp-bis#143]
The recommendation against this, plus the requirement to have all messages acknowledged, is not necessary.  DTLS implementations that have support for this feature might use it automatically and I see nothing in the design that would prevent it from being used, nor for the restrictions on use that are levied.

**Comment by martinthomson** [comment]
The answer was hidden in [this mega paragraph](https://gloinul.github.io/draft-westerlund-tsvwg-dtls-over-sctp-bis/draft-ietf-tsvwg-dtls-over-sctp-bis.html#section-4.7-1).  This might be pulled out into a clearer statement.

**Comment by gloinul** [comment]
Editoral improvement will be looked into.

**Comment by gloinul** [comment]
Starting to look at the issue here. I think we should consider to move the Section 4.8 on Renegotiation and Key Update into Section 3 instead as it appears to be more a DTLS consideration than actually a SCTP consideration for this solution. I think that section also motivates why Key Update does not work. Also as we not relying on this and instead the parallel DTLS connection it make sense to just clarify the DTLS requirement. Will write a PR proposing such a move and try to focus the text a bit more.

**Comment by gloinul** [comment]
So having thought more about this and had a bit of discussion among the authors. So we discussed that the issue with KeyUpdate could be resolved by not discarding the earlier keys, that would avoid any issues with expiring keys and the key turn over happening differently on different user messages. However, as DTLS only have the two lowest epoch bits in the packet format, when one have used keyUpdate four times one will have a uncertainty about which key it truly used if all are kept. Otherwise one must ensure that the old key is no longer in use and retire it. Getting us back to the problems that parallel DTLS deals with already. Thus, also this idea requires a DTLS implementation change, compared to just turning off the keyUpdate which appears to be a similar sized issue. So we don't see any benefit in allowing keyUpdate as it forces the requirement onto both side to function. Else one will drop the keys early. 

When it comes to draining the transmitter buffer before doing keyUpdate that requires API between the DTLS stack for when keyUpdate will happen so that these operations are synchronised as well as they are interfering with applications message flow during the draining by DTLS/SCTP adaptation layer. 

Thus, we conclude that simplest is simply to forbid keyUpdate and make it clear that the usage of parallel DTLS must ensure that the key material life time limits are followed.
