### ISSUE TITLE
Fallback?

### ISSUE THREAD

**Issue by tuexen** [gloinul/draft-westerlund-tsvwg-dtls-over-sctp-bis#17]
```
If the peer replies with an INIT-ACK not containing all DTLS/SCTP
Mandatory Options, the Client can decide to keep on working with
RFC 6083 fallaback, plain data only, or to ABORT the association.
```
How does this work? If the `RANDOM`, `CHUNKS`, or `HMAC-ALGO` parameter is missing, RFC 6083 does not work. So the only possibility is that `ADAPTATION-LAYER-INDICATION` is
missing or only SHA-1 is offered. That would mean RFC 6083 is used in combination with DTLS 1.2 or DTLS 1.3. I would vote for ABORTing. In the other cases, aren't we providing a way for downgrade attacks (SHA-256 -> SHA-1)?

**Comment by gloinul** [comment]
So, I  would note that the first section discuss the risks of fallback and recommend against it and requiring an explicit policy setting to enable it. Yes, it implies risking downgrade. 

This section discusses how an endpoint supporting this specification can fallback to follow the DTLS/SCTP behavior in RFC 6083. It is recommended to define a setting that represents the policy to allow fallback or not. However, the possibility to use fallback is based on the ULP can operate using user messages that are no longer than 16383 bytes. Fallback is NOT RECOMMEND to be enabled as it enables downgrade to weaker algorithms and versions of DTLS.

However, there are likely some transition cases that are going to need this. So doing RFC6083 with DTLS 1.2 or 1.3 is clearly possible. But the text do need a bit of update due to the change.

**Comment by gloinul** [comment]
Simplified the text to be more correct. I think the high level is correct now.
