### ISSUE TITLE
Resumption

### ISSUE THREAD

**Issue by emanjon** [gloinul/draft-westerlund-tsvwg-dtls-over-sctp-bis#76]
I looked into resumption a bit more and made an issue and a PR for RFC8446bis.

The question is if a ticket issued in connection N can be used in the parallel connection N+1. I see no reason why not except for the name "resumption".

RFC8446 is clear on that a ticket issued in connection N can be used to set up the connections N+2 and N+3 in parallel.

https://github.com/tlswg/tls13-spec/issues/1243
https://github.com/tlswg/tls13-spec/pull/1244

**Comment by emanjon** [comment]
The PR explainnig that resumption is allowed has been merged to RFC8446bis.

**Comment by emanjon** [comment]
I planned to do a PR but accidently commited directly to master. 28fa16d
Maybe it can be reviewed in master.

**Comment by emanjon** [comment]
I noted that the document does not give any guidance on tickets, but maybe this is ok or even the best solution.
Right now there can be any number of tickets issues in any connections.
If a connection uses resuption, the ticket can come from any previous connection.

As an example, something like the following is allowed by TLS 1.3:

1. Full handshake
2. Resumption with ticket from 1
3. Full handshake
4. Resumption with ticket from 2
5. Resumption with ticket from 3
6. Resumption with ticket from 1
7. Resumption with ticket from 3

**Comment by gloinul** [comment]
I think the changes looks good. With the many options regarding using tickets to do resumption for the new it is likely a feature. I think the only think we maybe need to think more about if there are interoperability issues here, so that one implementation do one set of resumption and the others only support another set and that results in failures. But if there are no such risks as the DTLS server roles will accept all, then I don't see an issue.

Also, do we need to clarify that if a resumption fails a full handshake fallback will be done, but I thought that this is implicit?

**Comment by emanjon** [comment]
I think it never results in failure. The only thing that can happen is that one of the parties throws away the ticket.
 - If the client does not have a ticket, the client does not offer resumption.
 - If the client offers resumption but also supply a "key_share" (RFC8446 says SHOULD do that) the server rejects resumption and a full handshake is performed.
 - If the client offers resumption but did not supply a "key_share", I think the server will send a HelloRetryRequest and the handshake will continue with the client sending a new clientHello with a "key_share".

I think TLS explains most of this, but maybe we would some clarification?
